"""add match scores to player_gw_stats

Revision ID: 88ec3d7dccb6
Revises: d26f389a8174
Create Date: 2026-07-24 19:35:38.161464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ec3d7dccb6'
down_revision: Union[str, Sequence[str], None] = 'd26f389a8174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gw_stats', sa.Column('team_h_score', sa.Integer(), nullable=True))
    op.add_column('player_gw_stats', sa.Column('team_a_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_gw_stats', 'team_a_score')
    op.drop_column('player_gw_stats', 'team_h_score')
    # ### end Alembic commands ###
