"""initial schema

Revision ID: d26f389a8174
Revises: 
Create Date: 2026-07-24 19:28:59.329168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26f389a8174'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_gw_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('element', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=False),
    sa.Column('fixture', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=48), nullable=True),
    sa.Column('opponent_team', sa.Integer(), nullable=True),
    sa.Column('was_home', sa.Boolean(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('starts', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('bps', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Float(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('ict_index', sa.Float(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('expected_assists', sa.Float(), nullable=True),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=True),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=True),
    sa.Column('clearances_blocks_interceptions', sa.Integer(), nullable=True),
    sa.Column('recoveries', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('defensive_contribution', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('transfers_in', sa.Integer(), nullable=True),
    sa.Column('transfers_out', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'event', 'element', 'fixture', name='uq_pgs_season_event_element_fixture')
    )
    op.create_index('ix_pgs_season_event', 'player_gw_stats', ['season', 'event'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_element_code'), 'player_gw_stats', ['element_code'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_event'), 'player_gw_stats', ['event'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_season'), 'player_gw_stats', ['season'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_snapshots_lookup', 'raw_snapshots', ['season', 'kind', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_snapshots_season'), 'raw_snapshots', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_snapshots_season'), table_name='raw_snapshots')
    op.drop_index('ix_raw_snapshots_lookup', table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index(op.f('ix_player_gw_stats_season'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_event'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_element_code'), table_name='player_gw_stats')
    op.drop_index('ix_pgs_season_event', table_name='player_gw_stats')
    op.drop_table('player_gw_stats')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
