// Single source of truth for the short explanations shown in <InfoTooltip>.
// Keep each entry to one plain-English sentence — these render in a small popover.
export const STAT_GLOSSARY = {
  ictIndex: "A single score combining Influence, Creativity and Threat to rank overall performance.",
  xgi: "Expected Goal Involvements: expected goals plus expected assists — how often a player's involved in a goal.",
  xg: "Expected Goals: the likelihood a player's shots result in a goal, based on shot quality.",
  xa: "Expected Assists: the likelihood a player's passes lead to a goal, based on chance quality.",
  form: "Average points per match over the player's last 30 days.",
  value: "Total points scored per £1m of price — a measure of value for money.",
  ownership: "The percentage of FPL managers who currently own this player.",
  fdr: "Fixture Difficulty Rating: 1 = easiest fixture, 5 = hardest, based on the opponent's strength.",
  avgFdr: "Average fixture difficulty across the gameweeks shown — lower means easier fixtures.",
  bonus: "Extra points (1–3) awarded to the best performers in a match, on top of base points.",
  bps: "Bonus Points System: the underlying score used to decide who gets bonus points each match.",
  xPts: "Our model's predicted FPL points for the gameweek(s) shown.",
  epNext: "Expected points for the very next gameweek only.",
  def90: "Defensive actions (tackles, interceptions, clearances, blocks) per 90 minutes played.",
  // Rates, not totals - the distinction is the whole point of showing them, so
  // every one of these says "per 90 minutes" explicitly rather than assuming the
  // reader infers it from the label.
  xg90: "Expected goals per 90 minutes played — shot quality at a rate, so a substitute isn't punished for playing less.",
  xa90: "Expected assists per 90 minutes played — chance creation at a rate, independent of minutes.",
  xgi90: "Expected goal involvements (goals plus assists) per 90 minutes played.",
  xgc90: "Expected goals conceded per 90 minutes, by this player's team while he's on — lower is better.",
  starts90: "Starts per 90 minutes played — near 1.0 means a regular starter rather than a substitute.",
  threat: "Opta's rating of how dangerous a player's attacking actions are. A season total, not a rate — FPL publishes no shot counts, so this is the closest available read on shot volume.",
  setPieceDuty: "Whether a player takes their club's corners, free-kicks or penalties.",
  netTransfers: "The difference between managers adding vs. removing this player recently.",
  transferRate: "How many managers are transferring this player in or out per hour.",
  cleanSheetProb: "Our model's estimated chance the player's team keeps a clean sheet.",
  ptsPerMillion: "Points scored per £1m of price — a value-for-money measure.",
  squadValue: "The total current market price of your 15 players.",
  benchStrength: "What your four bench players are predicted to score between them in the coming gameweek. Roughly what a Bench Boost would be worth.",
  benchBoost: "One-time chip: your bench's points count too, on top of your starting XI, for one gameweek.",
  tripleCaptain: "One-time chip: your captain scores triple points instead of double, for one gameweek.",
  freeHit: "One-time chip: unlimited free transfers for one gameweek only — your squad reverts after.",
  wildcard: "One-time chip: unlimited free transfers with no reverting afterwards.",
  captain: "Scores double points that gameweek.",
  viceCaptain: "Becomes captain automatically if your captain doesn't play.",
  minutes: "Total minutes played.",
  goals: "Goals scored.",
  assists: "Passes or actions that directly led to a goal.",
  cleanSheets: "Matches where the player's team didn't concede a goal.",
  gwPts: "Points scored in that single gameweek.",
  totalPts: "Total points scored so far this season.",
  price: "Current market value in £m — rises and falls with transfer activity.",
  budget: "Your total spending limit for the 15-man squad, in £m.",
  transferHit: "−4 points deducted for each transfer beyond your free transfers.",
  predictedXiWindow: "Your starting XI's combined predicted points across this whole window (captain's score doubled), after any transfer-hit deduction - not a single gameweek's score.",
  freeTransfers: "Transfers you can make this gameweek without a points penalty.",
  startingXi: "Your 11 selected starters, excluding the 4-player bench.",
  differentials: "Low-ownership players who could give you an edge over rivals.",
  outlook: "Players ranked by predicted points over the coming gameweeks.",
  score: "Our model's overall rating for the player, blending form, fixtures and underlying stats.",
  nextOpponent: "The opponent (and venue) for this player's next fixture.",
  role: "Whether the player is set to start, sit on the bench, or captain your team.",
  rank: "Position on the leaderboard, ranked by total points.",
  gwDeadline: "The gameweek this reading is taken from.",
  predictedGoals: "Our model's predicted number of goals for the period shown.",
  predictedAssists: "Our model's predicted number of assists for the period shown.",
  predictedPoints: "Our model's predicted FPL points for the period shown.",
  cardStatsIct: "ICT Index: a single score combining Influence, Creativity and Threat.",
  spent: "How much of your budget is currently allocated to your squad.",
  remaining: "Budget left unspent — money in the bank.",
  bankLeft: "Money left in the bank after this squad, unspent and available for future transfers.",
  positionScore: "The average Score (see above) of your starting players in this position - a 0-1+ rating that blends form, fixtures and underlying stats, not a points total.",
  window: "How many gameweeks ahead the optimizer plans transfers for.",
  asOf: "The gameweek data this plan is based on.",
  teamId: "Your FPL team's unique ID, found in the URL of your Points page on the official site.",
  goalInvolvements: "Goals plus assists combined.",
  xMins: "Our model's predicted minutes played.",
  defensiveContributions: "Tackles, interceptions, clearances and blocks combined — a new points category this season.",
  yellowCards: "Yellow cards received.",
  redCards: "Red cards received.",
} as const;

export type StatGlossaryKey = keyof typeof STAT_GLOSSARY;
